spring:
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/transaction/**