spring:
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/transaction/**
          filters:
            - AuthFilter
        - id: wallet-service
          uri: ${WALLET_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/account/**
          filters:
            - AuthFilter
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/user/**